//
//  Constants.swift
//  Movie Booking App
//
//  Created by Harry Jason on 06/06/2021.
//

import Foundation

var SEAT_TYPE_AVAILABLE = "AVAILABLE"
var SEAT_TYPE_TAKEN = "TAKEN"
var SEAT_TYPE_TEXT = "TEXT"
var SEAT_TYPE_EMPTY = "EMPTY"
var SEAT_TYPE_SELECTED = "SELECTED"

//UserDefault Keys
var KEY_USER_VO = "USER_VO"
var KEY_AUTH_TOKEN = "AUTH_TOKEN"
var KEY_SELECTED_MOVIE = "SELECTED_MOVIE"
var KEY_SELECTED_SEATS = "SELECTED_SEATS"
var KEY_SELECTED_SNACKS = "SELECTED_SNACKS"
var KEY_SELECTED_TIME_SLOT = "SELECTED_TIME_SLOT"
var KEY_SELECTED_CINEMA = "SELECTED_CINEMA"
var KEY_SELECTED_DATE = "SELECTED_DATE"

